### ISSUE TITLE
Huge jump in cpu/memory usage.

### ISSUE THREAD

**Issue by tombenton55** [colinbendell/homebridge-blink-for-home#25] opened 2020-11-16 08:46 UTC
Updated to the latest version and my cpu went from 2% to 67% memory has increased too. Had to uninstall as I don’t have a cooling solution yet. Thought I’d flag it just incase.

Edit seems to be related to live view, I’ve reinstalled and disabled it for now and cpu  everything is back to normal.

I’m using the new outdoor cam, I don’t need live view I was just testing it as the plug-in updated. Perhaps this is normal.

Sorry for my lack of technical ability

**Comment by xelypse** [comment] 2020-11-16 13:22
Same here. I had to turn off the power to the pi.

**Comment by colinbendell** [comment] 2020-11-16 13:38
Interesting. What configuration are you running? What version of homebridge? node? npm? To confirm, you updated and restarted homebridge and saw the increase in memory? Is it stable or does it drop?

**Comment by colinbendell** [comment] 2020-11-16 13:47
Using homebridge 1.2.3 and node 14, the active memory decreased ~10MB (read: within error bars) between 3.5.18 and 3.6.1. The big difference in this release is that I'm now using the HTTP/2 TLS socket APIs instead of H1. But that's a function of Node primarily.

**Comment by tombenton55** [comment] 2020-11-16 15:05
I'm using homebridge 1.2.3 on a pi4 2gb with node 14.15.0
As soon as I enabled the live view memory/cpu usage went crazy and stayed at 67-73%. 
Turning it off didn't help return it to normal. Plugin had to be uninstalled and reinstalled to fix.

Plugin without liveview has been absolutely flawless, I just got curious.

**Comment by xelypse** [comment] 2020-11-16 15:26
Node.js Version	v14.15.0
Npm Version	v6.14.8
Homebridge 1.1.6

**Comment by colinbendell** [comment] 2020-11-16 15:42
the re-install fixed the memory usage? After you did the update, did you restart homebridge?

**Comment by xelypse** [comment] 2020-11-16 17:49
yes, the Homebridge has been restarted.  The Pi also had to be restarted.  Then reinstall the plugin.  The same problem after a while.  Didn't reinstall the plugin.

**Comment by colinbendell** [comment] 2020-11-16 18:00
oh you mean the cpu + ram didn't spike immediately, but grew after a period of time?

**Comment by xelypse** [comment] 2020-11-16 18:20
Yes exactly.  It ran for a few minutes and suddenly the homebridge was unreachable, not even via ssh

**Comment by colinbendell** [comment] 2020-11-16 23:01
Oh. I think I misunderstood. You are using live view and found the cpu and memory go up. Is this correct? But under normal operation it doesn't? 

Live view uses ffmpeg to transcode the stream and so requires a high amount of cpu and memory to transcode and encrypt to meet HomeKit camera requirements. 

Can you confirm the use case you are finding this? 

If you are finding the high cpu/memory when not in live view, can you tell me if you are using a higher thumbnail refresh rate? Or the standard 10min when armed?

**Comment by tombenton55** [comment] 2020-11-16 23:19
Exactly. This was a live view specific situation.
If it’s normal behaviour then fine. But should it ramp up even when the
stream is exited?

**Comment by colinbendell** [comment] 2020-11-16 23:22
It might take a bit. But not long. Check the logs id it persists.

**Comment by xelypse** [comment] 2020-11-17 07:09
So for me the Pi is frozen twice in the default settings.  Before, all versions ran without problems.  I have now removed the plugin.

**Comment by mtressl** [comment] 2020-11-17 09:10
> So for me the Pi is frozen twice in the default settings. Before, all versions ran without problems. I have now removed the plugin.

Same situation here. Since the last update to 3.6.1 with no config changes this happens.

**Comment by nin9s** [comment] 2020-11-17 19:35
same here:
![image](https://user-images.githubusercontent.com/17455046/99438654-5cec3200-2914-11eb-975d-3670ab31ed20.png)

**Comment by dcgraves** [comment] 2020-11-17 19:49
I'm having the same issue and was able to get the CPU back down to normal levels by manually killing the ffmpeg process. From the behavior I noticed, it looks like ffmpeg starts when you click on a camera in the Home app for live view (even if you've disabled it) but it doesn't kill the ffmpeg process automatically once live view is exited.

**Comment by colinbendell** [comment] 2020-11-18 14:41
Thanks. I probably need to add a watcher to make sure the SIGINT/SIGKILL is properly sent. (PRs are always welcome ;)

**Comment by MasterofKungfu9999** [comment] 2020-11-25 14:35
Is there something new? I have this problem too.

**Comment by newelement** [comment] 2020-12-02 15:32
Tried this plugin today and seeing the same. CPU usage was around 4%, now it's around 50%. Could it be it's trying to stream the camera feeds in the background?

**Comment by colinbendell** [comment] 2020-12-08 14:53
The root cause is that the single frame image is being looped in ffmpeg and this process isn't getting killed gracefully. I haven't had time yet to add a timeout mechanism to clean up these events. (Usually happens when you go into the camera and then to settings). I'm planning to come back to this in the next week or so.

**Comment by newelement** [comment] 2020-12-08 15:15
> The root cause is that the single frame image is being looped in ffmpeg and this process isn't getting killed gracefully. I haven't had time yet to add a timeout mechanism to clean up these events. (Usually happens when you go into the camera and then to settings). I'm planning to come back to this in the next week or so.

@colinbendell No worries. This is awesome. If I had time I could help as well.

**Comment by saadatorama** [comment] 2020-12-16 16:04
I am also having the same issue. 

Node.js Version | v12.18.3
NPM v6.14.8
Rpi4 4GB

The plugin not only eats up my CPU but starts eating up my ram. Like OP, whenever I restart the machine it gets within normal range but within 30 min the entire Pi is at 100% CPU and nearly 100% RAM. Reinstalls and reconfigurations did nothing. 

Ultimately had to uninstall the plugin.

Let me know if I can provide further information to help you debug.

**Comment by jeremybdk** [comment] 2020-12-23 08:42
Same issue here, installed the plugin, when configured saw an increase to 100% of CPU Usage and 1.2 Gb or ram used by ffmpeg, I use a RPI 4 2Gb with node v12.20.0 and latest version of Homebridge.

I had to remove the plugin to get CPU and RAM to normal level, removing only the plugin configuration did not work.

**Comment by hunterpaul** [comment] 2021-01-01 19:43
Exactly the same issue for me too. CPU maxed out and the batteries in the camera got drained. Looks like a bug is keeping the live feed open

**Comment by saadatorama** [comment] 2021-02-08 17:52
Any update on this?

**Comment by robbie2003ie** [comment] 2021-02-08 18:26
Yeah, Any update? Unable to use as CPU shoots to 97% and will not go down until FFMPEG zombie process are killed.

**Comment by colinbendell** [comment] 2021-02-21 18:32
should be resolved in v3.7

**Closed by colinbendell** 2021-02-21 18:32 UTC
